AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'asedemoeol'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-secure-baseline'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'enrique-ochoa'
CICD_AGENT_TYPE: 'github'
CREATE_REDIS_RESOURCE: false
REDIS_TIER: 'Enterprise_E10'
